server:
  port: 9111
spring:
  datasource:
    hikari:
      maximum-pool-size: 20
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.169.183:3306/xinhxu?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 123456
crawler:
  type: douban
management:
  endpoints:
    web:
      exposure:
        include: '*'
# Mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.webcrawlerspringbootstarter.**.entity
# logger 配置
logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.web: error
    com.example.webcrawlerspringbootstarter: debug
